### ISSUE TITLE
unmask() does not work on IE7, IE8 (easy fix)

### ISSUE THREAD

**Issue by virbas** [flaviosilveira/Jquery-Price-Format#18]
unmask() does not work on IE7, IE8 
274: for(var f in field)  does not work on strings for those two browsers.
So change the whole loop to:
for(var f = 0; f < field.length; f++)
{
    if(!isNaN(field.charAt(f)) || field.charAt(f) == "-") result += field.charAt(f);
}

**Comment by flaviosilveira** [comment]
That was fixed in some commits ago.
Thanks a lot.
