### ISSUE TITLE
Add method to include default configuration on site

### ISSUE THREAD

**Issue by igorsantos07** [flaviosilveira/Jquery-Price-Format#32]
The plugin is awesome, but currently we need to call it with the options every time we need to format a field. Having different pages requesting the same format tends to give additional work since we need to have a global variable with the options, or keep repeating the config object on and on.

Would be cool to have something like `$.priceFormat.defaults = { [...] }` that we could run in the page header and then any call to `$('input').priceFormat()` would use those settings.

**Comment by flaviosilveira** [comment]
Done in the last release.
Thanks!
