### ISSUE TITLE
Problem in ClearOnEmpty in JqueryPlugin

### ISSUE THREAD

**Issue by extqy** [flaviosilveira/Jquery-Price-Format#40]
In line 221, include the function to_numbers() in parseFloat().

Em português:
Na linha 221, a função ParseFloat() não funciona corretamente quando o separador for uma virgula. Por isso, tem que adicionar a função to_numbers(), para que converta em numero antes.

Fiz um fork com essa correção, dê uma olhada depois

**Comment by rchamy** [comment]
Hi,
i had the same problem and i solved with the follow

                        // Formatted price as a value
			function price_it ()
			{
			    var str = get();
				var price = price_format(str);
				if (str != price) set(price);
				if (parseFloat(str.replace(/,/, '.')) == 0.0 && clearOnEmpty) set('');
			}
Then, i set the 'centsSeparator' property to ',' (comma) and is working now

Regards.
