### ISSUE TITLE
Can't clear the field!

### ISSUE THREAD

**Issue by Redani** [flaviosilveira/Jquery-Price-Format#45]
Hi, and thanks for your plugin!
I'm facing a little problem, when I clear the field, it keep 0 with the prefix value, is there a way to completely clear the text field and show the placeholder for example?

Thanks,
Regards

**Comment by rchamy** [comment]
Hi Redani,
Try to use this

$('#your-input').priceFormat({
                    prefix: '',
                    thousandsSeparator: '',
					clearOnEmpty: true
                });

Note that the 'clearOnEmpty' property is the solution for you.

Regards

**Comment by Redani** [comment]
Hi Rchamy, thank you so much for your reply :) it works like a charm, the version of plugin i was using doesn't have the "clearOnEmpty" option and I always thought i was using the latest one... :D

Have a great week end and once again thanks ;)

**Comment by rchamy** [comment]
You're welcome !
Also, i changed the following code to solve an issue in the script...

        // Formatted price as a value
        function price_it ()
        {
            var str = get();
            var price = price_format(str);
            if (str != price) set(price);
            /*Change this line for possible problems when you set the  'centsSeparator' property to ','        (comma) and the   'clearOnEmpty' property is set to true*/
            if (parseFloat(str.replace(/,/, '.')) == 0.0 && clearOnEmpty) set('');
        }


Regards.

**Comment by Redani** [comment]
Oh cool, thousand thanks ;)
Hope the author will make this update so it wont be overridden in the next updates... :)

Cheers

**Comment by Redani** [comment]
Hi again :) how are you?
I have just noticed that I can't enter the number 0, it's considered as being empty, is there a fix for that?
Thanks

**Comment by Redani** [comment]
No one has has an idea on how to fix this issue?? :/

**Comment by Redani** [comment]
Any updates regarding the problem of not being able to enter 0 ??

**Comment by flaviosilveira** [comment]
Soon..

**Comment by flaviosilveira** [comment]
Done!
