### ISSUE TITLE
Bug: clearOnEmpty: true

### ISSUE THREAD

**Issue by Redani** [flaviosilveira/Jquery-Price-Format#47]
Hi,

when clearOnEmpty is set to true, i have to enter the number twice, is there a fix for that?

Thanks

**Comment by cirelli** [comment]
Change the line 221 from `if(parseFloat(str) == 0.0 && clearOnEmpty) set('');` to `if (price == price_format('0', true) && clearOnEmpty) set('');`

**Comment by Redani** [comment]
Worked like a charm, thank you sooooo much :)

**Comment by Redani** [comment]
Hi again :)
I have detected another little bug :/ when you select all the text (Ctrl A) and then enter a number, it adds it at the end instead of replacing... Any idea on how to fix it?
Thanks
