### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by pvnr0082t** [flaviosilveira/Jquery-Price-Format#53]
Hi @flaviosilveira ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this library on cdnjs.
I found that the license info in `price-format.jquery.json` show `CDDL-1.0` on master branch and show `MIT` on v2.0.0 tagged release. Could you please help me check which license used for the repo?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8048

**Comment by webia1** [comment]
same issue: can we assume, the license is MIT ?

**Comment by flaviosilveira** [comment]
Hey Guys,
This is a MIT software.
I will fix the Json soon.

Sorry for that!
