### ISSUE TITLE
About version v2.0 and v2.0.0

### ISSUE THREAD

**Issue by pvnr0082t** [flaviosilveira/Jquery-Price-Format#55]
Hi @flaviosilveira ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs) team and we want to host this library.
I want to confirm that if the version `v2.0` is the same as `v2.0.0`. If yes, we'll just choose one of them and add it in cdnjs. Could you please confirm this? 
Thank you.

https://github.com/cdnjs/cdnjs/issues/8048
https://github.com/cdnjs/cdnjs/pull/8921

**Comment by flaviosilveira** [comment]
@pvnr0082t Please, use the v2.1
Thanks!

**Comment by pvnr0082t** [comment]
@flaviosilveira Yes, we'll add `v2.1` and also old versions. Or you mean both of `v2.0` and `v2.0.0` don't need to be added in cdnjs?

**Comment by flaviosilveira** [comment]
@pvnr0082t I see now. 2.0.0 was a mistake.
Please, consider just 2.0 and 2.1

Thanks!
