### ISSUE TITLE
PF is preventing jQuery '.change()' to work on Chrome (and IE)

### ISSUE THREAD

**Issue by slinstj** [flaviosilveira/Jquery-Price-Format#6]
I am using priceFormat() like usual, just flavored to pt_br currencies.

But i have a listener '.change' in a text input to call a function after to change the field. That text input is using priceFormat too. 

In FF, when i change the field, the function is called ok. Everything is working. But in Chrome (chromiun), the jquery change() event was not triggering.

After so many try/error i tryed to disable the priceFormat of that text input. For my surprise, change event is working for that input text now.

I have a customer that tryed in her IE 8 and the same problem occurs. I had not time to make tests on IE to proof it.

I dont have idea about what should be causing that, but it seems clear that priceFormat is preventing the jquery change() event to working in Chrome.

PriceFormat 1.5;
Firefox: 10.1;
Chromium	17.0.963.56 (Versão do desenvolvedor 121963) Ubuntu 11.10
SO	Linux
WebKit	535.11 (trunk@101876)
JavaScript	V8 3.7.12.22
Agente do usuário	Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.11 (KHTML, like Gecko) Ubuntu/11.10 Chromium/17.0.963.56 Chrome/17.0.963.56 Safari/535.11

**Comment by prashanthsnayak** [comment]
But in this simple [fiddle](http://jsfiddle.net/xLx580bk/), i have tried to use keyup and change event on same textbox and both works fine. This might be some other issue.

**Comment by prashanthsnayak** [comment]
Okay. Sorry, this is a [bug](https://code.google.com/p/chromium/issues/detail?id=92492) in chrome.
