### ISSUE TITLE
About removing the prototype support

### ISSUE THREAD

**Issue by nandomoreirame** [flaviosilveira/Jquery-Price-Format#70]
@flaviosilveira  what do you think about removing prototype?

The repo name is jQuery-Price-Format, why don't we move it to a repository called: "Prototype-Price-Format"?

**Comment by flaviosilveira** [comment]
You are right @nandomoreirame. I believe we can remove the file. It do not see an update since long long time.

I don't have interest in maintain a Prototype version.
