### ISSUE TITLE
Elemento criado dinamicamente

### ISSUE THREAD

**Issue by raphaelnikson** [flaviosilveira/Jquery-Price-Format#75]
Quando um elemento é criado dinamicamente não é possível aplicar a formatação?

**Comment by nandomoreirame** [comment]
Creio que sim @raphaelnikson , basta chamar o jQuery Price Format logo após o elemento ser adicionado ao DOM.

**Comment by raphaelnikson** [comment]
É verdade. noobice minha.. criei uma função e quando eu crio um elemento novo eu chamo ela pra poder aplicar o filtro novamente. 

valeu

**Comment by nandomoreirame** [comment]
👍
