### ISSUE TITLE
Formatação inicial incorreta. 

### ISSUE THREAD

**Issue by WalissonPires** [flaviosilveira/Jquery-Price-Format#83]
Olá Pessoal. Comecei a utilizar o plugin hoje e me deparei com uma situação.

Ao formatar um campo com valor 25 o plugin formatou o valor para 0.25. Se eu adicionar o mesmo valor com casa decimais (25,00) ele formata corretamente.

Esse problema pode ser verificado na página de exemplo onde é possível adicionar e remover a mascara do campo.

Enfim. Acredito que o correto é formatar 25 para 25.00.  (JS parseFloat(25) retornar 25 não 0.25). 

Desde já agradeço pela atenção.

**Comment by WalissonPires** [comment]
Agora percebi que o plugin trabalha com "centavos". 

Como a linguagem de back que uso por padrão retornar um float 25 como a string '25' isso se tornou um problema para mim. A intenção era usar o plugin para formatar as casas decimais. Mas devido essa forma de trabalho terei que fazer uma formatação adicional (adicionar ,00) antes que o plugin aplica a formatação.  :s

**Comment by douglasresende** [comment]
Encontrei uma lógica pra "burlar" esse cenário =)
```js
  function price_format (str)
  {
    if (str[str.length-3] == '.') {       // 1.11 # DO NOTHING
    } else if (str[str.length-2] == '.'){ // 1.1  # FILL WITH 1 ZERO
      str = str+"0"
    } else {                              // 1    # FILL WITH 2 ZEROS
      str = str+"00"
    }
```

**Comment by shadyueh** [comment]
There's a merge request needing a review that seems solve this problem https://github.com/price-format/Jquery-Price-Format/pull/88
